def showPSI(log, info):
        log.debug('PluginStartupInfo.StructSize={}'.format(info.StructSize))
        log.debug('PluginStartupInfo.ModuleName={}'.format(self.f2s(info.ModuleName)))
        log.debug('PluginStartupInfo.Menu={}'.format(info.Menu))
        log.debug('PluginStartupInfo.Message={}'.format(info.Message))
        log.debug('PluginStartupInfo.GetMsg={}'.format(info.GetMsg))
        log.debug('PluginStartupInfo.PanelControl={}'.format(info.PanelControl))
        log.debug('PluginStartupInfo.SaveScreen={}'.format(info.SaveScreen))
        log.debug('PluginStartupInfo.RestoreScreen={}'.format(info.RestoreScreen))
        log.debug('PluginStartupInfo.GetDirList={}'.format(info.GetDirList))
        log.debug('PluginStartupInfo.GetPluginDirList={}'.format(info.GetPluginDirList))
        log.debug('PluginStartupInfo.FreeDirList={}'.format(info.FreeDirList))
        log.debug('PluginStartupInfo.FreePluginDirList={}'.format(info.FreePluginDirList))
        log.debug('PluginStartupInfo.Viewer={}'.format(info.Viewer))
        log.debug('PluginStartupInfo.Editor={}'.format(info.Editor))
        log.debug('PluginStartupInfo.Text={}'.format(info.Text))
        log.debug('PluginStartupInfo.EditorControl={}'.format(info.EditorControl))

        log.debug('PluginStartupInfo.ShowHelp={}'.format(info.ShowHelp))
        log.debug('PluginStartupInfo.AdvControl={}'.format(info.AdvControl))
        log.debug('PluginStartupInfo.InputBox={}'.format(info.InputBox))
        log.debug('PluginStartupInfo.ColorDialog={}'.format(info.ColorDialog))
        log.debug('PluginStartupInfo.DialogInit={}'.format(info.DialogInit))
        log.debug('PluginStartupInfo.DialogRun={}'.format(info.DialogRun))
        log.debug('PluginStartupInfo.DialogFree={}'.format(info.DialogFree))

        log.debug('PluginStartupInfo.SendDlgMessage={}'.format(info.SendDlgMessage))
        log.debug('PluginStartupInfo.DefDlgProc={}'.format(info.DefDlgProc))
        log.debug('PluginStartupInfo.ViewerControl={}'.format(info.ViewerControl))
        log.debug('PluginStartupInfo.PluginsControl={}'.format(info.PluginsControl))
        log.debug('PluginStartupInfo.FileFilterControl={}'.format(info.FileFilterControl))
        log.debug('PluginStartupInfo.RegExpControl={}'.format(info.RegExpControl))
        log.debug('PluginStartupInfo.MacroControl={}'.format(info.MacroControl))
        log.debug('PluginStartupInfo.SettingsControl={}'.format(info.SettingsControl))
        log.debug('PluginStartupInfo.Private={}'.format(info.Private))
        log.debug('PluginStartupInfo.Instance={}'.format(info.Instance))
        log.debug('PluginStartupInfo.FreeScreen={}'.format(info.FreeScreen))

        #FARSTANDARDFUNCTIONS  *FSF;
